title: Jonathan Frazer
logo: /assets/img/me.jpg
description: Machine learning to address fundamental questions in evolution and health. Postdoc in the Marks lab, Harvard.
google_analytics: UA-118534303-1
theme: jekyll-theme-minimal
