title: Jonathan Frazer
logo: /assets/img/me.jpg
description: Theoretical physicist learning from the large scale structure of the universe and the large scale structure of the genome.
google_analytics: UA-118534303-1
theme: jekyll-theme-minimal
