title: Jonathan Frazer
logo: /assets/img/me.jpg
description: Theoretical physicist learning from the large scale structure of the universe and the large scale structure of the genome.
email: jonathangfrazer@gmail.com
twitter_username: jonnygfrazer
google_analytics:
theme: jekyll-theme-minimal
