title: Jonathan Frazer
description: Theoretical physicist learning from the large scale structure of the universe and the large scale structure of the genome. 
google_analytics:
theme: jekyll-theme-minimal
